[project]
name = "crewproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai[tools]>=0.165.1",
    "notebook>=7.4.5",
    "python-dotenv>=1.1.1",
]
